import { NextRequest, NextResponse } from 'next/server';
import { withAdminAIVerification } from '@/lib/ai-auth-middleware';
import { generateSocialMediaPost } from '@/ai/flows/generate-social-media-post';

async function handler(
  request: NextRequest,
  context: { uid: string; userProfile: any }
): Promise<NextResponse> {
  try {
    const body = await request.json();
    const {
      eventName,
      eventDate,
      eventLocation,
      eventDescription,
      targetAudience = 'local residents',
      callToAction = 'register now',
      desiredTone = 'friendly',
    } = body;

    // Validate required fields
    if (!eventName || !eventDate || !eventLocation || !eventDescription) {
      return NextResponse.json(
        { error: 'Missing required fields: eventName, eventDate, eventLocation, eventDescription' },
        { status: 400 }
      );
    }

    // Generate social media post using AI (platform is not required by flow)
    const result = await generateSocialMediaPost({
      eventName,
      eventDate,
      eventLocation,
      eventDescription,
      targetAudience,
      callToAction,
      desiredTone,
    });

    // Log AI usage for admin tracking
    console.log(`[AI USAGE] Social media post generated by admin ${context.userProfile.email} for event "${eventName}"`);

    return NextResponse.json({
      success: true,
      postContent: result.postContent,
      hashtags: result.hashtags,
      eventName,
      eventDate,
      eventLocation,
      desiredTone,
      generatedBy: context.userProfile.email,
      generatedAt: new Date().toISOString()
    });

  } catch (error) {
    console.error('Error generating social media post:', error);
    return NextResponse.json(
      { error: 'Failed to generate social media post' },
      { status: 500 }
    );
  }
}

export const POST = withAdminAIVerification(handler);