import { NextRequest, NextResponse } from 'next/server';
import { withAdminAIVerification } from '@/lib/ai-auth-middleware';
import { suggestEngagementMessage } from '@/ai/flows/suggest-engagement-message';

async function handler(
  request: NextRequest,
  context: { uid: string; userProfile: any }
): Promise<NextResponse> {
  try {
    const body = await request.json();
    const { volunteerName, lastParticipationDate, totalEventsAttended, preferredCommunicationStyle = 'friendly' } = body;

    // Validate required fields
    if (!volunteerName || !lastParticipationDate || totalEventsAttended === undefined) {
      return NextResponse.json(
        { error: 'Missing required fields: volunteerName, lastParticipationDate, totalEventsAttended' },
        { status: 400 }
      );
    }

    // Validate data types
    if (typeof totalEventsAttended !== 'number') {
      return NextResponse.json(
        { error: 'totalEventsAttended must be a number' },
        { status: 400 }
      );
    }

    // Validate communication style
    const validStyles = ['friendly', 'professional', 'casual', 'motivational'];
    if (!validStyles.includes(preferredCommunicationStyle)) {
      return NextResponse.json(
        { error: `Invalid communication style. Must be one of: ${validStyles.join(', ')}` },
        { status: 400 }
      );
    }

    // Generate engagement message using AI
    const result = await suggestEngagementMessage({
      volunteerName,
      lastParticipationDate,
      totalEventsAttended,
      preferredCommunicationStyle: preferredCommunicationStyle as 'friendly' | 'professional' | 'casual' | 'motivational'
    });

    // Log AI usage for admin tracking
    console.log(`[AI USAGE] Engagement message generated by admin ${context.userProfile.email} for volunteer "${volunteerName}"`);

    return NextResponse.json({
      success: true,
      message: result.message,
      volunteerData: {
        volunteerName,
        lastParticipationDate,
        totalEventsAttended,
        preferredCommunicationStyle
      },
      generatedBy: context.userProfile.email,
      generatedAt: new Date().toISOString()
    });

  } catch (error) {
    console.error('Error generating engagement message:', error);
    return NextResponse.json(
      { error: 'Failed to generate engagement message' },
      { status: 500 }
    );
  }
}

export const POST = withAdminAIVerification(handler);