import { NextRequest, NextResponse } from 'next/server';
import { withAdminAIVerification } from '@/lib/ai-auth-middleware';
import { generateCertificateText } from '@/ai/flows/generate-certificate-text-flow';

async function handler(
  request: NextRequest,
  context: { uid: string; userProfile: any }
): Promise<NextResponse> {
  try {
    const body = await request.json();
    const { volunteerName, eventName, eventDate } = body;

    // Validate required fields
    if (!volunteerName || !eventName || !eventDate) {
      return NextResponse.json(
        { error: 'Missing required fields: volunteerName, eventName, eventDate' },
        { status: 400 }
      );
    }

    // Generate certificate text using AI
    const result = await generateCertificateText({
      volunteerName,
      eventName,
      eventDate
    });

    // Log AI usage for admin tracking
    console.log(`[AI USAGE] Certificate text generated by admin ${context.userProfile.email} for volunteer ${volunteerName}`);

    return NextResponse.json({
      success: true,
      certificateText: result.certificateText,
      generatedBy: context.userProfile.email,
      generatedAt: new Date().toISOString()
    });

  } catch (error) {
    console.error('Error generating certificate text:', error);
    return NextResponse.json(
      { error: 'Failed to generate certificate text' },
      { status: 500 }
    );
  }
}

export const POST = withAdminAIVerification(handler);