import { NextRequest, NextResponse } from 'next/server';
import { withAdminAIVerification } from '@/lib/ai-auth-middleware';
import { summarizeCleanupEvent } from '@/ai/flows/summarize-cleanup-event';

async function handler(
  request: NextRequest,
  context: { uid: string; userProfile: any }
): Promise<NextResponse> {
  try {
    const body = await request.json();
    const { 
      eventName, 
      location, 
      date, 
      totalVolunteers, 
      totalWasteCollectedKg, 
      typesOfWasteCollected, 
      notableObservations 
    } = body;

    // Validate required fields
    if (!eventName || !location || !date || totalVolunteers === undefined || totalWasteCollectedKg === undefined) {
      return NextResponse.json(
        { error: 'Missing required fields: eventName, location, date, totalVolunteers, totalWasteCollectedKg' },
        { status: 400 }
      );
    }

    // Validate data types
    if (typeof totalVolunteers !== 'number' || typeof totalWasteCollectedKg !== 'number') {
      return NextResponse.json(
        { error: 'totalVolunteers and totalWasteCollectedKg must be numbers' },
        { status: 400 }
      );
    }

    // Generate cleanup event summary using AI
    const result = await summarizeCleanupEvent({
      eventName,
      location,
      date,
      totalVolunteers,
      totalWasteCollectedKg,
      typesOfWasteCollected: typesOfWasteCollected || '',
      notableObservations: notableObservations || ''
    });

    // Log AI usage for admin tracking
    console.log(`[AI USAGE] Cleanup event summary generated by admin ${context.userProfile.email} for event "${eventName}"`);

    return NextResponse.json({
      success: true,
      summary: result.summary,
      eventData: {
        eventName,
        location,
        date,
        totalVolunteers,
        totalWasteCollectedKg,
        typesOfWasteCollected,
        notableObservations
      },
      generatedBy: context.userProfile.email,
      generatedAt: new Date().toISOString()
    });

  } catch (error) {
    console.error('Error summarizing cleanup event:', error);
    return NextResponse.json(
      { error: 'Failed to summarize cleanup event' },
      { status: 500 }
    );
  }
}

export const POST = withAdminAIVerification(handler);