import { NextRequest, NextResponse } from 'next/server';
import { withAdminAIVerification } from '@/lib/ai-auth-middleware';
import { generateEventImage } from '@/ai/flows/generate-event-image-flow';

async function handler(
  request: NextRequest,
  context: { uid: string; userProfile: any }
): Promise<NextResponse> {
  try {
    const body = await request.json();
    const { 
      eventName, 
      eventDescription, 
      eventDate,
      eventLocation,
      format = 'poster',
      style = 'modern',
      colorScheme = 'blue-green',
      designTheme = 'charity',
      callToAction = '',
      additionalPrompt = ''
    } = body;

    // Validate required fields
    if (!eventName || !eventDescription) {
      return NextResponse.json(
        { error: 'Missing required fields: eventName, eventDescription' },
        { status: 400 }
      );
    }

    // Validate format
    if (!['poster', 'banner'].includes(format)) {
      return NextResponse.json(
        { error: 'Invalid format. Must be "poster" or "banner"' },
        { status: 400 }
      );
    }

    // Generate event image using AI
    const result = await generateEventImage({
      eventName,
      eventDescription,
      eventDate: eventDate || '',
      eventLocation: eventLocation || '',
      format: format as 'poster' | 'banner',
      style: style || 'modern',
      colorScheme: colorScheme || 'blue-green',
      designTheme: designTheme || 'charity',
      callToAction: callToAction || '',
      additionalPrompt: additionalPrompt || ''
    });

    // Log AI usage for admin tracking
    console.log(`[AI USAGE] Event image generated by admin ${context.userProfile.email} for event "${eventName}"`);

    return NextResponse.json({
      success: true,
      imageDataUri: result.imageDataUri,
      eventName,
      format,
      generatedBy: context.userProfile.email,
      generatedAt: new Date().toISOString()
    });

  } catch (error) {
    console.error('Error generating event image:', error);
    return NextResponse.json(
      { error: 'Failed to generate event image' },
      { status: 500 }
    );
  }
}

export const POST = withAdminAIVerification(handler);